SuperMovie/Controllers/api/TvShowController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Http;
using SuperMovie.Dtos;
using SuperMovie.Models;

namespace SuperMovie.Controllers.Api
{

    public class TvShowController : ApiController
    {
        private ApplicationDbContext _context;

        public TvShowController()
        {
            _context = new ApplicationDbContext();
        }

        public IEnumerable<TvShowDto> GetTvShow()
        {
            return _context.TvShows
                .Include(t => t.Genre)
                .ToList()
                .Select(Mapper.Map<TvShow, TvShowDto>);
        }

        public IHttpActionResult GetTvShow(int id)
        {
            var tvshow = _context.TvShows.SingleOrDefault(t => t.Id == id);

            if (tvshow == null)
                return NotFound();

            return Ok(Mapper.Map<TvShow, TvShowDto>(tvshow));
        }



        [HttpPost]
        [System.Web.Mvc.Authorize(Roles = RoleName.CanManageMovies)]
        public IHttpActionResult CreateTvShow(TvShowDto tvshowDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var tvshow = Mapper.Map<TvShowDto, TvShow>(tvshowDto);
            _context.TvShows.Add(tvshow);
            _context.SaveChanges();

            tvshowDto.Id = tvshow.Id;
            return Created(new Uri(Request.RequestUri + "/" + tvshow.Id), tvshowDto);
        }

        [HttpPut]
        [System.Web.Mvc.Authorize(Roles = RoleName.CanManageMovies)]
        public IHttpActionResult UpdateTvShow(int id, TvShowDto tvshowDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var tvshowInDb = _context.TvShows.SingleOrDefault(t => t.Id == id);

            if (tvshowInDb == null)
                return NotFound();

            Mapper.Map(tvshowDto, tvshowInDb);

            _context.SaveChanges();

            return Ok();
        }

        [HttpDelete]
        [System.Web.Mvc.Authorize(Roles = RoleName.CanManageMovies)]
        public IHttpActionResult DeleteTvShow(int id)
        {
            var tvshowInDb = _context.TvShows.SingleOrDefault(t => t.Id == id);

            if (tvshowInDb == null)
                return NotFound();

            _context.TvShows.Remove(tvshowInDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}

SuperMovie/Views/Shared/_Layout.cshtml
@using SuperMovie.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/ionicons.min.css" rel="stylesheet">
    <title>Super Movie</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Mvc.RazorTools.BundleManager.Styles.Render()

</head>
<body>
            @if (User.IsInRole(RoleName.CanManageMovies))
               { 
                   @Html.Partial("_NavBar")
               }
            else
               {
                   @Html.Partial("_NavBar -guest")
               }
                
        
    
<div class="container body-content">
    @RenderBody()
  
    <section class="container col-md-12" style="overflow-x:auto;">
        <hr />
        <footer class="row">

            <div class="col-md-6">
                <ul class="footer-nav">
                    <li><a href="">ABOUT US</a></li>
                    <li><a href=""><img src="~/Content/Img/iCloud.png" style="height: 32px; width: 100px;"></a></li>
                    <li><a href=""><img src="~/Content/Img/android.png" style="width: 90px; height: 30px;"></a></li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="social-links">
                    <li><a href=""><i class="fa fa-facebook"></i></a></li>
                    <li><a href=""><i class="fa fa-twitter"></i></a></li>
                    <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                    <li><a href=""><i class="fa fa-instagram"></i></a></li>

                </ul>
            </div>
            <div>
                <p>
                    Copyright &copy; 2018 by Super Movie. All rights reserved.
                </p>
            </div>

        </footer>
    </section>

</div>


@Scripts.Render("~/bundles/lib")
@RenderSection("scripts", required: false)
</body>
</html>

SuperMovie/Views/Shared/_NavBar -guest.cshtml
@using System.Drawing
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("Index", "Home")"><img src="~/Content/Img/planets-clipart-neon-11.png" style="z-index: 1; width: 60px; height: 60px;"></a>
            
      @*@Html.ActionLink(, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                
            
                    <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                    <li>@Html.ActionLink("TV Show", "Index", "TvShow")</li>
                
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                
                

              
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

SuperMovie/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("Index", "Home")"><img src="~/Content/Img/planets-clipart-neon-11.png" style="z-index: 1; width: 60px; height: 60px;"></a>
          @*@Html.ActionLink("Smovie", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                <li>@Html.ActionLink("TV Show", "Index", "TvShow")</li>
                <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>